apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "campaign-orchestrator.fullname" . }}
  labels:
    {{- include "campaign-orchestrator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "campaign-orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "campaign-orchestrator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "campaign-orchestrator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "campaign-orchestrator.apiKeySecretName" . }}
                  key: {{ include "campaign-orchestrator.apiKeySecretKey" . }}
          envFrom:
            - secretRef:
                name: {{ include "campaign-orchestrator.fullname" . }}-env
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/healthcheck
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/healthcheck
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
