{{- include "campaign-orchestrator.apiKeyValidation" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "campaign-orchestrator.fullname" . }}-env
  labels:
    {{- include "campaign-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  PRODUCTION: {{ .Values.app.production | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}
  BASE_URL: {{ .Values.app.baseUrl | quote }}
  SERVER_PORT: {{ .Values.service.port | quote }}
  SERVER_WORKERS: {{ .Values.app.serverWorkers | quote }}
  {{- if not .Values.app.apiKeyExistingSecret.enabled }}
  API_KEY: {{ .Values.app.apiKey | quote }}
  {{- end }}
  SYSTEM_NAME: {{ .Values.app.systemName | quote }}
  BROKER_HOST: {{ .Values.broker.host | quote }}
  BROKER_PORT: {{ .Values.broker.port | quote }}
  BROKER_PROTOCOL: {{ .Values.broker.protocol | quote }}
  BROKER_USERNAME: {{ .Values.broker.username | quote }}
  BROKER_PASSWORD: {{ .Values.broker.password | quote }}
  MINIO_URI: {{ .Values.app.minio.uri | quote }}
  MINIO_USERNAME: {{ .Values.app.minio.username | quote }}
  MINIO_PASSWORD: {{ .Values.app.minio.password | quote }}
  CAMPAIGN_REPOSITORY_BACKEND: {{ .Values.campaignRepository.backend | quote }}
  {{- if .Values.broker.tlsCert }}
  BROKER_TLS_CERT: {{ .Values.broker.tlsCert | quote }}
  {{- end }}
  {{- if eq .Values.campaignRepository.backend "mongo" }}
  CAMPAIGN_REPOSITORY_MONGO_URI: {{ printf "mongodb://%s:%s@%s/?authSource=admin" .Values.campaignRepository.mongo.auth.rootUsername .Values.campaignRepository.mongo.auth.rootPassword (include "campaign-orchestrator.mongo.serviceName" .) | quote }}
  CAMPAIGN_REPOSITORY_MONGO_DB: {{ .Values.campaignRepository.mongo.auth.database | quote }}
  {{- end }}
  {{- if eq .Values.campaignRepository.backend "postgres" }}
  CAMPAIGN_REPOSITORY_POSTGRES_DSN: {{ printf "postgresql://%s:%s@%s/%s" .Values.campaignRepository.postgres.auth.username .Values.campaignRepository.postgres.auth.password (include "campaign-orchestrator.postgres.serviceName" .) .Values.campaignRepository.postgres.auth.database | quote }}
  {{- end }}
